### ISSUE TITLE
Request for release of realme GT 6 vendor and kernel source code

### ISSUE THREAD

**Issue by cherinyy** [realme-kernel-opensource/realme_GTneo6_GTneo6SE-AndroidU-kernel-source#4]
Please release the [realme GT 6](https://www.realme.com/global/realme-gt-6) vendor and kernel source code.

**Comment by Khan-Noor** [comment]
@realme-kernel-opensource  please release GT 6T source also

**Comment by cherinyy** [comment]
https://github.com/realme-kernel-opensource/realmeGT6-AndroidU-kernel-source
https://github.com/realme-kernel-opensource/realmeGT6-AndroidU-vendor-source
